markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: https://github.com/wangyuansxya/wangyuansxya.github.io
author: "wangyuan"
email: wangyuansxya@163.com
name: "wangyuan个人博客"
url: https://wangyuansxya.github.io/
domain: https://wangyuansxya.github.io/
all_categories: [
["android", "Android开发","/posts/android.html"], 
["ios", "IOS开发","/posts/ios.html"],
["git", "git相关","/posts/git.html"], 
["linux", "Linux相关","/posts/linux.html"],
["read", "读书笔记","/posts/read.html"], 
["other", "杂记","/posts/other.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: China/Beijing

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
